name:                ofmc-parallel
version:             0.1.0.0
github:              "JakuJ/ofmc-parallel"
license:             BSD3
author:              "Jakub Janaszkiewicz"
maintainer:          "janaszkiewicz.jakub@gmail.com"
copyright:           "2022 Jakub Janaszkiewicz"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/JakuJ/ofmc-parallel#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- array
- parallel

default-extensions:
- ScopedTypeVariables
- NoMonomorphismRestriction

ghc-options:
- -O2
- -Wno-tabs
- -fspec-constr-count=5
- -eventlog
- -fprof-auto
- -fno-prof-count-entries

library:
  source-dirs: src

executables:
  ofmc-parallel:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ofmc-parallel
